disabled_rules:
  - trailing_newline
  - cyclomatic_complexity
  - function_body_length
  - type_body_length
  - file_length
  - multiple_closures_with_trailing_closure
  - implicit_optional_initialization
  - nesting
  - trailing_comma
  - opening_brace

opt_in_rules:
  - empty_count
  - empty_string

included:
  - frontend/SuperSay/SuperSay

excluded:
  - Pods
  - build
  - .DS_Store
  - frontend/SuperSay/SuperSayTests

identifier_name:
  min_length: 1
  max_length: 60
  excluded:
    - vm
    - id
    - to
    - s
    - k
    - v
    - i
    - p
    - m
    - v1
    - v2

line_length: 200

force_unwrapping:
  severity: warning

force_cast:
  severity: warning
